# Generated by Django 3.2.5 on 2021-07-25 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('order', '0003_alter_orderitem_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
