# Generated by Django 3.2.5 on 2021-07-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderitem_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
