# Generated by Django 3.2.5 on 2021-07-26 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20210725_2150'),
        ('order', '0005_auto_20210725_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='code',
            field=models.IntegerField(verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='delivery_address',
            field=models.CharField(max_length=100, verbose_name='адресс доставки'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='payed',
            field=models.BooleanField(default=False, verbose_name='оплачено'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('unpaid', 'неоплачен'), ('cooking', 'готовится'), ('delivering', 'доставляется'), ('received', 'получен')], default='unpaid', max_length=100, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='menu.product', verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='code',
            field=models.IntegerField(verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='payed',
            field=models.BooleanField(default=False, verbose_name='оплачено'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='restaurant',
            field=models.CharField(choices=[('loc1', 'Первый ресторан'), ('loc2', 'Второй ресторан'), ('loc3', 'Третий ресторан')], max_length=100, verbose_name='ресторан'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='status',
            field=models.CharField(choices=[('unpaid', 'неоплачен'), ('cooking', 'готовится'), ('ready', 'готов'), ('received', 'получен')], max_length=100, verbose_name='статус'),
        ),
    ]
