# Generated by Django 3.2.5 on 2021-07-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210726_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuporder',
            name='status',
            field=models.CharField(choices=[('unpaid', 'неоплачен'), ('cooking', 'готовится'), ('ready', 'готов'), ('received', 'получен')], default='unpaid', max_length=100, verbose_name='статус'),
        ),
    ]
