# Generated by Django 3.2.5 on 2021-07-26 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_pickuporder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 23, 26, 56, 503160)),
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 23, 26, 56, 503160)),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='delivery_address',
            field=models.CharField(max_length=100, verbose_name='адрес доставки'),
        ),
    ]
