# Generated by Django 3.2.5 on 2021-07-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210726_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
