# Generated by Django 3.2.5 on 2021-07-26 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20210726_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryorder',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='pickuporder',
            options={'ordering': ['-date']},
        ),
    ]
