# Generated by Django 3.2.5 on 2021-07-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20210728_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='session_id',
            field=models.CharField(default=0, max_length=150),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='session_id',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
