# Generated by Django 3.2.5 on 2021-07-24 19:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(max_length=100, verbose_name='кухня')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=30000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена продукта')),
                ('quantity', models.PositiveIntegerField()),
                ('picture', models.URLField()),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(3000)])),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='menu.cuisine')),
            ],
        ),
    ]
