# Generated by Django 3.2.5 on 2021-07-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuisine',
            old_name='cuisine',
            new_name='name',
        ),
    ]
